spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/fitness?authSource=admin
      database: fitness
  logging:
    level:
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  kafka:
    bootstrap-server: localhost:9092
    producer:
      key-serializer:  org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    name: activity-events

server:
 port: 8081


eureka:
     client:
       serviceUrl:
         defaultZone: http://localhost:8761/eureka/


