spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/fitness?authSource=admin
      database: fitness
  logging:
    level:
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG

server:
 port: 8081


eureka:
     client:
       serviceUrl:
         defaultZone: http://localhost:8761/eureka/
